version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ../:/var/www/html
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=docker-server"
    depends_on:
      - mariadb
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: 