#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Swagger UI route
app.swagger:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

# Optional: JSON format documentation
app.swagger.json:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_json }